import type { Metadata } from "next";
import "./globals.css";
import NavPage from "./component/nav";
import { Poppins } from "next/font/google";
import SeclectDropdown from "./component/SelectDropdown";
import Footer from './component/Footer';




const poppins = Poppins({
  subsets: ["latin"],
  weight: [
    "100","200","300","400","500",
    "600","700","800","900"
  ],
  style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
       <NavPage/>
       {/*<SeclectDropdown/>*/}
        {children}


<Footer/>




      </body>
    </html>
  );
}
